### ISSUE TITLE
Crash when re-attaching window

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#70]
When dragging a tab out and then right-click inside its terminal and click Re-attach, Ásbrú crashes without warning or anything.

See also https://sourceforge.net/p/pacmanager/bugs/160/

**Comment by gfrenoy** [comment]
@nugzarg

Not sure if this is exactly the same but detaching and then re-attaching a connection (possibly several times) will eventually crash on Àsbrú with the following error:

    “./asbru-cm” terminated by signal SIGSEGV (Address boundary error)

Note sure how to debug this further.  Any help will be appreciated.

**Comment by gfrenoy** [comment]
By running ```perl -d ./asbru-cm```, I receive a few more details:

```
Signal SEGV at /asbru-cm/lib/PACTerminal.pm line 1413.
	PACTerminal::__ANON__[/asbru-cm/lib/PACTerminal.pm:1413] called at /asbru-cm/lib/PACUtils.pm line 1582
	PACUtils::__ANON__[/asbru-cm/lib/PACUtils.pm:1582](Gtk2::Action=HASH(0x603b9f8)) called at /asbru-cm/lib/PACMain.pm line 368
	eval {...} called at /asbru-cm/lib/PACMain.pm line 368
	PACMain::start(PACMain=HASH(0x16ef1a8)) called at ./asbru-cm line 124
```

but it's not always the same:

```
Signal SEGV at /asbru-cm/lib/PACTerminal.pm line 2160.
	eval {...} called at /asbru-cm/lib/PACTerminal.pm line 2160
	PACTerminal::_winToTab(PACTerminal=HASH(0x187aa68)) called at /asbru-cm/lib/PACTerminal.pm line 1416
	PACTerminal::__ANON__[/asbru-cm/lib/PACTerminal.pm:1416] called at /asbru-cm/lib/PACUtils.pm line 1582
	PACUtils::__ANON__[/asbru-cm/lib/PACUtils.pm:1582](Gtk2::Action=HASH(0x516e258)) called at /asbru-cm/lib/PACMain.pm line 368
	eval {...} called at /asbru-cm/lib/PACMain.pm line 368
	PACMain::start(PACMain=HASH(0xada1b8)) called at ./asbru-cm line 124
```

By using ```gdb```, I see the following:

```
Thread 1 "perl" received signal SIGSEGV, Segmentation fault.
0x00007ffff4ba8eef in magazine_cache_trim (allocator=0x7ffff4e53240 <allocator>, stamp=<optimised out>, ix=<optimised out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gslice.c:679
```

And backtrace (bt) gives:

```
#0  0x00007ffff4ba8eef in magazine_cache_push_magazine (allocator=0x7ffff4e53240 <allocator>, stamp=<optimised out>, ix=<optimised out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gslice.c:679
#1  0x00007ffff4ba8eef in magazine_cache_push_magazine (ix=<optimised out>, magazine_chunks=<optimised out>, count=<optimised out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gslice.c:710
#2  0x00007ffff4baa1b2 in g_slice_free1 (tmem=<optimised out>, ix=6) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gslice.c:809
#3  0x00007ffff4baa1b2 in g_slice_free1 (mem_size=<optimised out>, mem_block=0x3ed29d0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gslice.c:1118
#4  0x00007ffff03b9c2b in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#5  0x00007ffff03b9c5e in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#6  0x00007ffff4b8d197 in g_main_context_dispatch (context=0xee2c00) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3154
#7  0x00007ffff4b8d197 in g_main_context_dispatch (context=context@entry=0xee2c00) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3769
#8  0x00007ffff4b8d3f0 in g_main_context_iterate (context=0xee2c00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimised out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3840
#9  0x00007ffff4b8d712 in g_main_loop_run (loop=0x3ef1800) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4034
#10 0x00007ffff0744697 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#11 0x00007ffff0cfde85 in  () at /usr/lib/x86_64-linux-gnu/perl5/5.22/auto/Gtk2/Gtk2.so
#12 0x00000000004bd41a in Perl_pp_entersub ()
#13 0x00000000004b62c6 in Perl_runops_standard ()
#14 0x0000000000443aed in perl_run ()
#15 0x000000000041cb2b in main ()
```

Some other findings:

- Detaching windows looks to be OK (I detached 10 different tabs without any problem)
- If I re-attach or simply close a detached tab, it crashes very quickly
- Only closing a detached tab may cause a crash
- A right click on a terminal after a detached window has been closed causes a crash
- Must be related to #52

As usual, any kind of help will be appreciated.  I guess we would need to find someone that is comfortable with Gtk / Glib etc and that would explain how to debug this further.

**Comment by gfrenoy** [comment]
This issue does not happen with the newest released (based on GTK3).

See also #327

**Comment by skuran** [comment]
Asbru 6.0.4 on Ubuntu 16.04 still having the same issue. This bug existed in pac-manager too. Any update?

**Comment by gfrenoy** [comment]
This issue is marked as fixed so you should not expect any update...
